%% Generated by ../../scripts/lilypond-book.py
%% Options: [raggedright,indent=0\mm,verbatim,fragment,quote,relative=1]

\paper {
  #(define dump-extents #t)
  raggedright = ##t
  indent = 0\mm
  linewidth = 160\mm - 2.0 * 0.4\in
}

\layout {
  
}

\relative c'
{
% ly snippet contents follows:
\new PianoStaff <<
  \new Staff { \time 2/4 c4\sustainDown c g' g }
  \new Staff { \clef bass c,, c' e c }
>>

% end ly snippet
}